In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("Churn_Modelling.csv")

In [4]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:
len(data.columns)

14

In [22]:
#separating dependent and independent features
x = data.iloc[:,3:13]
y = data.iloc[:,13:]

In [30]:
#converting geography and gender to categorical
geo = pd.get_dummies(x["Geography"],drop_first=True)

In [31]:
gender = pd.get_dummies(x["Gender"],drop_first=True)

In [32]:
#concating
x = pd.concat([x,geo,gender],axis=1)

In [35]:
x = x.drop(["Geography","Gender"],axis=1)

In [36]:
x.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0

In [37]:
  #splitting the data into train and test data
from sklearn.model_selection import train_test_split

In [38]:
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [39]:
x_train.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
7389          667   34       5       0.00              2          1   
9275          427   42       1   75681.52              1          1   
2995          535   29       2  112367.34              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain  Male  
7389               0        163830.64        0      1     0  
9275               1         57098.00        1      0     1  
2995               0        185630.76        0      0     0

In [40]:
## feature scaling
from sklearn.preprocessing import StandardScaler

In [41]:
ss = StandardScaler()

In [42]:
x_train = ss.fit_transform(x_train)

In [43]:
x_test = ss.fit_transform(x_test)

In [45]:
x_train #-1 t0

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [64]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [65]:
#initializing ANN
#empty ANN
classifier = Sequential()

In [66]:
#adding 1st hidden layer
classifier.add(Dense(units=10,kernel_initializer='he_uniform',activation='relu',input_dim =11))
# 11 -- col

In [67]:
#adding 2nd hidden layer
classifier.add(Dense(units=20,kernel_initializer='he_uniform',activation='relu'))

In [68]:
classifier.add(Dense(units=20,kernel_initializer='he_uniform',activation='relu'))

In [69]:
#adding output layer
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

In [70]:
#compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [71]:
#fitting
model = classifier.fit(x_train,y_train,validation_split= 0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 [==============================] - 3s 4ms/step - loss: 0.4805 - accuracy: 0.7901 - val_loss: 0.4548 - val_accuracy: 0.8039
Epoch 2/100
536/536 [==============================] - 3s 5ms/step - loss: 0.4275 - accuracy: 0.8166 - val_loss: 0.4316 - val_accuracy: 0.8179
Epoch 3/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3954 - accuracy: 0.8388 - val_loss: 0.4052 - val_accuracy: 0.8262
Epoch 4/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3718 - accuracy: 0.8475 - val_loss: 0.3959 - val_accuracy: 0.8307
Epoch 5/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3599 - accuracy: 0.8548 - val_loss: 0.3875 - val_accuracy: 0.8387
Epoch 6/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3522 - accuracy: 0.8546 - val_loss: 0.3835 - val_accuracy: 0.8451
Epoch 7/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3462 - accuracy: 0.8556 - val_loss: 0.3842 - val_accuracy: 0.8432

In [81]:
y_pred = classifier.predict(x_test)

63/63 [==============================] - 0s 1ms/step


In [82]:
y_pred = y_pred>0.5

In [74]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [83]:
#conufusion metrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [84]:
cm

array([[1467,  128],
       [ 168,  237]])

In [85]:
#accuracy
from sklearn.metrics import accuracy_score

In [86]:
score = accuracy_score(y_pred,y_test)

In [87]:
score

0.852